## Import Dashboard
# https://artifacthub.io/packages/helm/grafana/grafana

dashboards:
  default:
    #some-dashboard:
    #  json: |
    #    {
    #      "annotations":

    #      ...
    #      # Complete json file here
    #      ...

    #      "title": "Some Dashboard",
    #      "uid": "abcd1234",
    #      "version": 1
    #    }
    #custom-dashboard:
    #  # This is a path to a file inside the dashboards directory inside the chart directory
    #  file: dashboards/custom-dashboard.json
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/2
      gnetId: 2
      revision: 2
      datasource: Prometheus
    #local-dashboard:
    #  url: https://raw.githubusercontent.com/user/repository/master/dashboards/dashboard.json


ingress:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "ovh-issuer"
  enabled: true
  hosts:
    - "monitoring.olblak.com"
  path: /grafana
  tls:
    - secretName: "monitoring-olblak-com-tls"
      hosts:
        - monitoring.olblak.com

grafana.ini:
  server:
    root_url: http://localhost:3000/grafana # this host can be localhost
